/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/delorean-dmc12-retro-wave-art-6b18d3a8859749379987380bf2ac34ab
Title: DeLorean DMC12 || Retro wave art
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/assets/models/delorean_dmc12__retro_wave_art.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.419, 0.579, -1.061]} rotation={[0, -0.783, -Math.PI / 2]} scale={1.203}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_16 as any).geometry}
          material={materials.base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_17 as any).geometry}
          material={materials.base}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_4 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, -Math.PI / 2]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_6 as any).geometry}
        material={materials.details}
        position={[6.354, 0.92, -4.008]}
        rotation={[0.169, -0.776, 0.119]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_8 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_10 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_12 as any).geometry}
        material={materials.details}
        position={[3.416, 0.577, -1.058]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_14 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, -Math.PI / 2]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_19 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, -Math.PI / 2]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_21 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[Math.PI / 2, 0, 0.783]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_23 as any).geometry}
        material={materials.details}
        position={[0.337, 0.579, 2.033]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_25 as any).geometry}
        material={materials.details}
        position={[-0.368, 0.713, 2.694]}
        rotation={[-0.328, -0.756, 2.912]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_27 as any).geometry}
        material={materials.sphere}
        position={[3.78, -0.747, -8.385]}
        rotation={[0, 1.228, 0]}
        scale={52.195}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_29 as any).geometry}
        material={materials.emis}
        position={[3.78, -0.715, -8.385]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_31 as any).geometry}
        material={materials.material}
        position={[-46.163, -1.682, 6.744]}
        rotation={[-2.905, 1.271, 2.897]}
        scale={[2.496, 2.642, 2.332]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_33 as any).geometry}
        material={materials.material}
        position={[3.78, 9.376, -53.733]}
        scale={2.64}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_35 as any).geometry}
        material={materials.material}
        position={[6.344, 8.63, -53.609]}
        rotation={[0, -0.032, 0]}
        scale={2.64}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_37 as any).geometry}
        material={materials.material}
        position={[45.504, -1.275, 7.24]}
        rotation={[0, -1.525, 0]}
        scale={2.64}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_39 as any).geometry}
        material={materials.material}
        position={[2.847, -1.275, 37.888]}
        rotation={[-0.072, 0.256, 0]}
        scale={[1.923, 2.64, 1.891]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_41 as any).geometry}
        material={materials.material}
        position={[35.563, -1.682, 33.915]}
        rotation={[-3.049, -0.717, -3.099]}
        scale={[2.496, 2.642, 2.332]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_43 as any).geometry}
        material={materials.material}
        position={[-24.174, -1.275, 25.635]}
        rotation={[-Math.PI, 0.277, -Math.PI]}
        scale={2.64}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_45 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_47 as any).geometry}
        material={materials.glass}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, -Math.PI / 2]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_49 as any).geometry}
        material={materials.details}
        position={[3.441, 0.574, -1.083]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_51 as any).geometry}
        material={materials.details}
        position={[3.43, 0.574, -1.072]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_53 as any).geometry}
        material={materials.details}
        position={[3.431, 0.579, -1.073]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_55 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_57 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_59 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_61 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_63 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_65 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_67 as any).geometry}
        material={materials.details}
        position={[3.646, 0.579, -1.287]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_69 as any).geometry}
        material={materials.details}
        position={[3.645, 0.579, -1.288]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_71 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_73 as any).geometry}
        material={materials.mountains}
        position={[3.639, -1.636, 16.98]}
        scale={[1.267, 0.915, 0.664]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_75 as any).geometry}
        material={materials.emis_blue}
        position={[3.639, -1.636, 16.98]}
        scale={[1.267, 0.915, 0.664]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_77 as any).geometry}
        material={materials.details}
        position={[6.404, 0.938, -4.058]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_79 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_81 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_83 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_85 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_87 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_89 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_91 as any).geometry}
        material={materials.material_8}
        position={[3.78, 9.376, -53.733]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.192}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_93 as any).geometry}
        material={materials.terain_main}
        position={[3.78, -0.747, -8.385]}
        rotation={[0, 1.228, 0]}
        scale={52.195}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_95 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_97 as any).geometry}
        material={materials.details}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_99 as any).geometry}
        material={materials.wheels}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_101 as any).geometry}
        material={materials.wheels}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_103 as any).geometry}
        material={materials.wheels}
        position={[6.396, 0.037, -1.301]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_105 as any).geometry}
        material={materials.wheels}
        position={[3.419, 0.579, -1.061]}
        rotation={[0, -0.783, 0]}
        scale={1.203}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Object_107 as any).geometry}
        material={materials.wheels}
        position={[3.032, 0.579, -0.672]}
        rotation={[0, -0.783, Math.PI / 2]}
        scale={1.203}
      />
    </group>
  )
}

useGLTF.preload('/assets/models/delorean_dmc12__retro_wave_art.glb')
